version: '3'

services:
  # PostgreSQL with PostGIS
  db:
    #image: postgis/postgis:16-3.4
    image: kartoza/postgis
    container_name: postgres-postgis
    environment:
      POSTGRES_DB: jobfinder
      POSTGRES_USER: job123
      POSTGRES_PASSWORD: job123
    ports:
      - "15432:5432"
    networks:
      - pg-network
    volumes:
      - /home/synapios/ilisilab/pg-data:/var/lib/postgresql/data

  # PGAdmin4
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ilisi@gmail.com
      PGADMIN_DEFAULT_PASSWORD: ilisip
    ports:
      - "15050:80"
    depends_on:
      - db
    networks:
      - pg-network
    volumes:
      - /home/synapios/ilisilab/pgadmi-data:/var/lib/pgadmin4/ilisi@gmail.com

  # Redis
  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - pg-network
    volumes:
      - redis-data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Application Spring Boot
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: jobfinder
    ports:
      - "8092:8091"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/jobfinder
      SPRING_REDIS_HOST: redis
      SPRING_REDIS_PORT: 6379
    depends_on:
      - db
      - redis
    networks:
      - pg-network

networks:
  pg-network:
    driver: bridge

#volumes:
#  pg-data:
#  pgadmin-data:
#  redis-data:
