version: '3'

services:
  # PostgreSQL with PostGIS
  db:
    #image: postgis/postgis:16-3.4
    image: kartoza/postgis
    container_name: postgres-postgis
    environment:
      POSTGRES_DB: jobfinder
      POSTGRES_USER: job123
      POSTGRES_PASSWORD: job123
    ports:
      - "15432:5432"
    networks:
      - app-network
    volumes:
      - /home/synapios/ilisilab/pg-data:/var/lib/postgresql/data

  # PGAdmin4
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ilisi@gmail.com
      PGADMIN_DEFAULT_PASSWORD: ilisi
    ports:
      - "15050:80"
    depends_on:
      - db
    networks:
      - app-network
    volumes:
      - /home/synapios/ilisilab/pgadmi-data:/var/lib/pgadmin4/ilisi@gmail.com

  # Redis
  redis:
    image: redis:latest
    container_name: redis-container
    ports:
      - "6379:6379"
    networks:
      - app-network
    volumes:
      - /home/synapios/ilisilab/redis-data:/data
    command: [ "redis-server", "--appendonly", "yes" ]

networks:
  app-network:
    driver: bridge

#volumes:
#  pg-data:
#  pgadmin-data:
#  redis-data:
